inputParameter:
  num_of_variation: 2
  summerization_prompt: "یک خلاصه از توضیح محصول که در زیر آورده شده بنویس.  خلاصه جامع باشد. لطفا عنوان  خلاصه توضیح را در جواب ننویس. فقط خلاصه را بنویس"
  key_points_prompt: "ویژگی های مهم این محصول آموزشی  و مبحث هایی که پوشش میدهد را با توجه به توضیح داده شده لیست کن. فقط ویژگی ها و مباحث را بنویس و عنوان بندی نکن. پاسخ بدون هیچ گونه علائم خط تیره و ستاره و ... باشد."
